version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.17
jobs:
  aws-cli-gatsby:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: gatsby
      - run: 
          name: Install Node and NPM
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install nodejs build-essential libssl-dev
            
      - run:
          name: Build and deploy
          command: |
            npm install && npm run build && npm run deploy

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-gatsby