version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.17
jobs:

  deploy-stg:
    executor: aws-cli/default
    steps:

      - run: 
          name: Install Node and NPM
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install nodejs build-essential libssl-dev
          
      - checkout

      - aws-cli/setup:
        profile-name: gatsby
            
      - run:
          name: Build and Deploy to stg
          command: |
            export DEPLOY_BUCKET=candidate-tax-matrix-2020-stg
            npm install && npm run build && npm run deploy

  deploy-live:
    executor: aws-cli/default
    steps:

      - run: 
          name: Install Node and NPM
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install nodejs build-essential libssl-dev      

      - checkout

      - aws-cli/setup:
        profile-name: gatsby
            
      - run:
          name: Build and Deploy to stg
          command: |
            export DEPLOY_BUCKET=candidate-tax-matrix-2020
            npm install && npm run build && npm run deploy

workflows:
  version: 2
  aws-cli:
    jobs:
      - deploy-stg:
          filters:
            branches:
              only:
                - staging
 
      - deploy-live:
          filters:
            branches:
              only:
                - master