version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.17
jobs:

  prepare-env:
    executor: aws-cli/default
    steps:
      - run: 
          name: Install Node and NPM
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install nodejs build-essential libssl-dev

      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: NPM Install
          command: npm install

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

      # - run:
      #     name: Build and deploy
      #     command: |
      #       npm run build && npm run deploy

  deploy-stg:
    executor: aws-cli/default
    steps:
      - checkout

      - aws-cli/setup:
        profile-name: gatsby

      - attach_workspace:
          at: .
            
      - run:
          name: Build and Deploy to stg
          command: |
            export DEPLOY_BUCKET=candidate-tax-matrix-2020-stg
            npm run build && npm run deploy


  deploy-live:
    executor: aws-cli/default
    steps:
      - checkout

      - aws-cli/setup:
        profile-name: gatsby

      - attach_workspace:
          at: .
            
      - run:
          name: Build and Deploy to stg
          command: |
            export DEPLOY_BUCKET=candidate-tax-matrix-2020
            npm run build && npm run deploy

workflows:
  version: 2
  aws-cli:
    jobs:
      - prepare-env:
          filters:
            branches:
              only:
                - master
                - live

      - deploy-stg:
          filters:
            branches:
              only:
                - master
      

      - deploy-live:
          filters:
            branches:
              only:
                - WDT-3251/ci-cd