version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.17
jobs:
  aws-cli-gatsby:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: gatsby
      - run: npm install && npm run build && npm run deploy
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-gatsby:
          context: aws